import { Inter } from "next/font/google";
import "../styles/globals.css";
import { ThemeProvider } from "../context/themeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RichInbox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
