import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Provider from "@/provider/Provider";
import { ThemeProvider } from "@/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body className={inter.className}>
          <Provider>{children}</Provider>
        </body>
      </ThemeProvider>
    </html>
  );
}
